export const products = [
  {
    id: 1,
    title: 'Bolsa Eclipse Lunar',
    price: 80,
    description: 'Bolsa em crochê feita à mão, com design marcante e estilo único.',
    images: ['/bolsa.jpeg'],
    category: 'mais vendidos',
  },
  {
    id: 2,
    title: 'Top Paparazzi',
    price: 75,
    description: 'Top em crochê feito à mão, ideal pra looks cheios de atitude.',
    images: ['/top.jpeg'],
    category: 'mais vendidos',
  },
  {
    id: 3,
    title: 'Bolsa Baguete',
    price: 399,
    description: 'Bolsa baguete em crochê, perfeita pra produções modernas.',
    images: ['/bolsa-baguete-batom.jpeg'],
    category: 'bolsas',
  },
  {
    id: 5,
    title: 'Bolsa Camesin',
    price: 349,
    description: 'Bolsa artesanal em crochê, prática e cheia de personalidade.',
    images: ['/bolsa-camesin.jpeg'],
    category: 'bolsas',
  },
  {
    id: 6,
    title: 'Bolsa Duo',
    price: 349,
    description: 'Bolsa em crochê com design versátil, ideal pro dia a dia.',
    images: ['/bolsa-roxa.jpeg'],
    category: 'bolsas',
  },
  {
    id: 7,
    title: 'Bolsa Praia',
    price: 349,
    description: 'Bolsa de praia em crochê, espaçosa e estilosa.',
    images: ['/bolsa-praia.jpeg'],
    category: 'bolsas',
  },
  {
    id: 8,
    title: 'Headpiece EG',
    price: 349,
    description: 'Headpiece em crochê feito à mão, criado pra roubar a cena.',
    images: ['/headpiece.png'],
    category: 'mais vendidos',
  },
  {
    id: 9,
    title: 'Headpiece LG',
    price: 349,
    description: 'Headpiece artesanal com design marcante e cheio de atitude.',
    images: ['/headpiece-branco.png'],
    category: 'headpieces',
  },
  {
    id: 10,
    title: 'Regata',
    price: 349,
    description: 'Regata em crochê feita à mão, leve e estilosa.',
    images: ['/top.png'],
    category: 'tops',
  },
  {
    id: 11,
    title: 'Regata',
    price: 349,
    description: 'Regata em crochê com cor vibrante e visual moderno.',
    images: ['/regata-verde.jpeg'],
    category: 'tops',
  },
  {
    id: 12,
    title: 'Regata',
    price: 349,
    description: 'Regata artesanal em crochê, perfeita pro dia a dia.',
    images: ['/regata.jpeg'],
    category: 'tops',
  },
  {
    id: 13,
    title: 'Cybershot',
    price: 349,
    description: 'Saquinho em crochê feito à mão para proteger e estilizar sua câmera.',
    images: ['/cyberhsot.png'],
    category: 'variados',
  },
];
